services:
  iptv-au:
    container_name: iptv-au
    image: matthuisman/iptv-au
    environment:
      - REGION=all
      - APP_DATA_DIR=/data/iptv-au-docker
    ports:
      - 8183:80
    volumes:
      - iptv-au-data:/data
    restart: unless-stopped

volumes:
  iptv-au-data:
